### PR TITLE
ex: added buffer ids, :b lists buffers and :b# selects buffer

### PR DESCRIPTION
**Pull request by cjwagenius**

### CODE REVIEW

**Comment by aligrudi** [comment]
"C.J.Wagenius" <notifications@github.com> wrote:
> -- Commit Summary --
> 
>   * ex: added buffer ids, :b lists buffers and :b# selects buffer

Thanks.  The patch looks good and I have tested it.  I modified
ex.c not to reuse buffer ids when bufs array is filled (otherwise
two buffers can get identical ids) and also to show a message
when the given id does not exist.

I am now considering how helpful this command is in typical use
cases.  I do not expect to use it myself.

	Ali

**Comment by cjwagenius** [comment]
It just makes it convenient to switch between buffers if you got many of them open. Instead of :e [path], if not the alternate buffer, it's more convenient to type :b3. You usually can remember which ids you want under a session. 
Two buffers should not get the same id, but the id should be replaced with another buffer. This is intentional to replace buffers rarely used.

/cjw

**Comment by aligrudi** [comment]
"C.J.Wagenius" <notifications@github.com> wrote:
> It just makes it convenient to switch between buffers if you got
> many of them open. Instead of :e [path], if not the alternate buffer,
> it's more convenient to type :b3. You usually can remember which ids
> you want under a session.

OK.  I'll push it into the buffers branch.

> Two buffers should not get the same id, but the id should be
> replaced with another buffer. This is intentional to replace buffers
> rarely used.

Try changing the size of bufs to 3 and try:

  :e mot.c
  :e ex.c
  :e vi.c
  :b3
  :e vi.h
  :b

	Ali

**Comment by cjwagenius** [comment]
Sorry. Didn't notice that memset.

**Comment by cjwagenius** [comment]
Sorry. This is getting messy. I don't have full insight into github and pull requests. Maybe we should remove this request, since there are commits not having to do anything with buffers in it.

**Pull request closed without merging**
