### PR TITLE
honor umask and a little saner placeholder defaults

### PR DESCRIPTION
**Pull request by aaronNGi**
I added caret notation placeholders for all control characters to conf.h. Newline and tab included but they are commented out.

Instead of hardcoding the mode argument of `open(2)` to `0600`, I used `umask(2)`.

### CODE REVIEW

**Comment by aaronNGi** [comment]
Bump.

I want to package `neatvi` for [KISS Linux](https://getkiss.org/) but would like to wait for this to get merged first. Any chance?

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> I want to package `neatvi` for [KISS Linux](https://getkiss.org/)
> but would like to wait for this to get merged first. Any chance?

Sorry for late reply.

About the umask patch, note that open() automatically takes umask
into account and there is no need to do so manually.  The access
mode passed to open is very restrictive in Neatvi, though.

For the placeholder patch, I personally prefer "�" as a placeholder
for nonprintable characters (I check them with visual-mode command ga).
Neatvi is not good at editing binary files.

Thanks,
Ali

**Comment by aaronNGi** [comment]
> Sorry for late reply.

No problem, I just wanted to make sure you haven't simply missed it.

> About the umask patch, note that open() automatically takes umask
into account and there is no need to do so manually.  The access
mode passed to open is very restrictive in Neatvi, though.

Right, I'm a big newbie 🤦‍♂️ Are you opposed to changing the mode to 0666 though?

> For the placeholder patch, I personally prefer "�" as a placeholder
for nonprintable characters (I check them with visual-mode command ga).
Neatvi is not good at editing binary files.

I should have tested `neatvi` more thoroughly. I could've sworn I saw it not interpreting most control characters at all (I probably mixed it up with some other vi-clone I was testing at the time). While I would still prefer caret notation, I have to agree that the current default behaviour is sufficient enough.

I will wait for your answer regarding a change to 0666 before closing this pull request.

**Comment by aligrudi** [comment]
Aaron G <notifications@github.com> wrote:
> I will wait for your answer regarding a change to 0666 before closing this pull request.

Added MKFILE_MODE macro to conf.h.

Thanks,
Ali

**Comment by aaronNGi** [comment]
Good solution, thank you.

**Pull request closed without merging**
