### PR TITLE
gg to goto top

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by kyx0r** [comment]
Not sure if Ali wants to add more non posix features, but I have this implemented in my version. In case you haven't seen it:https://github.com/kyx0r/nextvi also has a lot more features to offer.

**Comment by jumps-are-op** [comment]
Did not know `gg` wasn't a POSIX vi feature. Good to know.

**Comment by lobre** [comment]
Shoud this PR be closed then?

**Comment by mattn** [comment]
yes, thank you

**Pull request closed without merging**
